---
- name: Generate the Sensu client config file. 
  template:
    src: client.json.j2
    dest: /etc/sensu/conf.d/clients/{{ item }}
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: "u=rw,g=r,o=r"
  with_items:
    - client.json

- name: enable sensu-client to survive reboot
  service:
    name=sensu-client
    enabled=yes


- name: Install sensu-plugin - a framework for writing Sensu plugins & handlers with Ruby.
  gem: 
    name: sensu-plugin  
    state: latest 
    #executable=/opt/sensu/embedded/bin/gem 

- name: Install Standard Plugins - CPU.
  gem: 
    name: sensu-plugins-cpu-checks 
    state: latest 
    #executable=/opt/sensu/embedded/bin/gem 

- name: Install Standard Plugins - RAM.
  gem: 
    name: sensu-plugins-memory-checks 
    state: latest 
    #executable=/opt/sensu/embedded/bin/gem 

- name: Install Standard Plugins - Disks.
  gem: 
    name: sensu-plugins-disk-checks 
    state: latest 

- name: Install Standard Plugins - Load Average.
  gem: 
    name: sensu-plugins-disk-checks 
    state: latest 

- name: Install Standard Plugins - Network.
  gem: 
    name: sensu-plugins-network-checks 
    state: latest 

- name: Install Standard Plugins - Process.
  gem: 
    name: sensu-plugins-process-checks
    state: latest
    
