---
# Restarting the Sensu monitoring framework
- name: Restart Sensu Server.
  service: 
    name: sensu-{{ item }} 
    state: restarted
  with_items:
    - server
    - api
  when: sensu_install_server

- name: Restart Sensu Client.
  service: 
    name: sensu-{{ item }} 
    state: restarted
  with_items:
    - client
  when: sensu_install_client

- name: Restart uchiwa DC.
  service: 
    name: sensu-{{ item }} 
    state: restarted
  with_items:
    - uchiwa
  when: sensu_install_uchiwa