---
# Restarting the Sensu monitoring framework
- name: Start Sensu Server.
  service: 
    name: sensu-{{ item }} 
    state: started
  with_items:
    - server
    - api
  when: sensu_install_server

- name: Start Sensu Client.
  service: 
    name: sensu-{{ item }} 
    state: started
  with_items:
    - client
  when: sensu_install_client

- name: Start uchiwa DC.
  service: 
    name: uchiwa
    state: started
  when: sensu_install_uchiwa