---
- name: Generate rabbitmq config files.
  template:
    src: rabbitmq.json.j2
    dest: /etc/sensu/conf.d/sensu-framework/{{ item }}
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: "u=rw,g=r,o=r"
  with_items:
    - rabbitmq.json