---
- name: Install sensu-plugin - a framework for writing Sensu plugins & handlers with Ruby.
  gem: 
    name: sensu-plugin  
    state: latest 
    #executable=/opt/sensu/embedded/bin/gem 

- name: Copy the 
  copy:
    src: {{ sensu_cert_dir }}/{{ item }}
    dest: /etc/sensu/ssl/{{ item }}
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: "u=rw,g=r,o="
    backup: yes
  with_items:
    - "{{ sensu_cert_file_name }}"
    - "{{ sensu_key_file_name }}"


- name: copy the handlers files
  copy:
    src=files/sensu/handlers/
    dest=/etc/sensu/handlers/
    owner=sensu
    group=sensu
    mode=0750

- name: copy extension files
  copy:
    src=files/sensu/extensions/
    dest=/etc/sensu/extensions/
    owner=sensu
    group=sensu
    mode=0750
  notify:
    - restart sensu server

- name: copy plugins files
  copy:
    src=files/sensu/plugins/
    dest=/etc/sensu/plugins/
    owner=sensu
    group=sensu
    mode=0750
  notify:
    - restart sensu server

- name: generate config files
  template:
    src={{ item }}.json.j2
    dest=/etc/sensu/conf.d/{{ item }}.json
    owner=sensu
    group=sensu
    mode=0640
  with_items:
    - handlers
    - redis
    - api
    - settings
    - checks
  notify:
    - Restart Sensu Server

- name: Start sensu-{server,api} and make it survive a reboot
  service:
    name=sensu-{{ item }}
    enabled=yes
    state=started
  with_items:
    - server
    - api