---
- name: Adduser cso | Create the cso group
  group: 
    name: cso 
    state: present

- name: Adduser cso | Initial admin user creation - cso.
  user: 
    name: cso   
    shell: /bin/bash
    password: "{{ 'init_password' }}" 
    update_password: on_create
    createhome: yes
    home: /home/cso 
    groups: cso,sudo,admins,sshusers
    append: yes
  register: cso

- name: Adduser cso | Create .ssh/ directory in cso home directory  
  file: 
    path: /home/cso/.ssh 
    state: directory
    owner: cso
    group: cso  
    mode: "u=rw,g=rw,o=r"

- name: Adduser cso | Adding the cso public key to authorized_keys files.
  authorized_key: 
    user: cso 
    key: "{{ lookup('file', '/root/.ssh/cso_rsa.pub') }}"

- name: Adduser cso | User cso will have to change password at first connection.
  shell: chage -d 0 cso
  when: cso.changed
