
---
- name: Check if the rancher-agent is running, normally it doesn't !  
  command: docker ps -a
  register: containers

- name: Register the Host machine with the Rancher server
  docker:
      image: rancher/agent:v1.0.1
      privileged: yes
      detach: True
      volumes: /var/run/docker.sock:/var/run/docker.sock
      command: https://cloud.minsys.io/v1/scripts/6F2DD31AB021F1CA6831:1464037200000:mKT4prP9XU31QdBgVQqnAZI
      state: started
  when: "{{ 'rancher-agent' not in containers.stdout }}"
