---
# Main Tasks File : installing a sensu server for every DC @ cloud.minsys.io.  
# Inspired by https://github.com/Mayeu/ansible-playbook-sensu, thanks @ Mayeu. 
# Workflow inpired by Scott Lee's, @ DigitalOcean. 
# Thanks @ scottlee https://www.digitalocean.com/community/users/scottlee.

- include: common.yaml

- include: client_rabbitmq-conf.yaml

- include: client_conf-base.yaml


- include: sclient_conf-standard_OS_checks.yaml


- include: postinstall.yaml
  when: sensu_install_client

- include: uchiwa.yaml
  when: sensu_install_uchiwa

- include: post_install.yaml
  when: sensu_install_uchiwa