---
 
 - name: "init_password"    
   prompt: "Enter a password for the user lvi"    
   private: yes    
   encrypt: "md5_crypt" #need to have python-passlib installed in local machine before we can use it    
   confirm: yes    
   salt_size: 7