---
- name: Install build-essential.
  apt: 
    name: build-essential 
    state: present

- name: Add ruby stable repository from PPA and install its signing key, thanks @ https://www.brightbox.com/docs/ruby/ubuntu/#Addingtherepository
  apt_repository: 
    repo: 'ppa:brightbox/ruby-ng'

- name: Refresh apt cache with "apt-get update"
  apt: 
    update_cache: yes

- name: Install Ruby 2.2 & the dev packages so you can build native extensions
  apt: 
    name: ruby{{ item }}  
    state: present
  with_items:
    - 2.2
    - 2.2-dev

- name: Add the official Sensu repository's key.
  apt_key: 
    url: http://sensu.global.ssl.fastly.net/apt/pubkey.gpg
    state: present

- name: Add the official Sensu repository.
  copy:
    src: aptrepo_sensu-server.list
    dest: /etc/apt/sources.list.d/
    backup: yes
  register: aptrepo

- name: Refresh apt cache with "apt-get update"
  apt: 
    update_cache: yes

- name: Install Sensu, the monitoring framework.
  apt: 
    name: sensu 
    state: present

- name: Enable sensu-client to survive reboot.
  service: 
    name: sensu-{{ item }} 
    enabled: yes
  with_items:
    - client

