---
ansible_ssh_user: root
ansible_ssh_private_key_file: /root/.ssh/ovh-root_rsa

fail2ban:
  config:
    ignoreip: 127.0.0.1/8
    bantime: 600
    findtime: 600
    maxretry: 3
    backend: auto
    usedns: warn
    destemail: root@localhost
    sendername: Fail2Ban
    banaction: iptables-multiport
    mta: sendmail
    protocol: tcp
    chain: INPUT

