---
ansible_ssh_user: root
ansible_ssh_private_key_file: /root/.ssh/scw-root_rsa
#addusers:
#  upassword: "{{ init_password }}"
#- name: "add new user"
#  user: name="{{user_name}}" 
#  comment: "{{ description_user }}"
# password: "{{user_password}}" home: "{{home_dir}}" shell: "/bin/bash" 