#to do 
#Eclater le scrpit en plusieurs roles !!!!  
#0°)update & upgrade

#1°)timezone
#2°)Modifier les fichiers /etc/hostname et /etc/hosts
#3°)DynDNS ? 
#4°)Add user lvi 
#5°)Add user cso 
#6°)Fail2ban 




---
- name: Check the current time zone 
  shell: cat /etc/timezone
  register: current_tzone  

- name: Set timezone variables to Europe/Paris
  copy: 
    content: "{{ my_tzone }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: current_tzone.stdout != my_tzone
  notify: update_timezone

- name: Create the primary group -admins- for leading users.
  group: 
    name: admins 
    state: present

- name: Add ansible user to the admins group 
  user: 
    name: ansible
    groups: admins
    append: yes 

- name: Create the lvi group
  group: 
    name: lvi 
    state: present

- name: Create the cso group 
  group: 
    name: cso 
    state: present


- name: Initial admin user creation - lvi.
  user: 
    name: lvi 
    password: "{{ addusers.config.upassword }}"  
    comment: laurent.vincentelli@minsys.io 
    shell: /bin/bash 
    createhome: yes 
    home: /home/lvi 
    groups: lvi,admins,sudo,sshusers
    append: yes
    
- name: Initial admin user creation - cso.
  user: 
    name: cso 
    password: "{{ addusers.config.upassword }}" 
    comment: cyril.szecsko@zesteinformatique.com 
    shell: /bin/bash 
    createhome: yes 
    home: /home/cso
    groups: cso,admins,sudo,sshusers
    append: yes
    
- name: Users lvi & cso will have to change password at first connection.
  shell: chage -M 1 lvi && chage -M 1 cso

- name: Create .ssh/ directory in lvi home directory  
  file: 
    path: /home/lvi/.ssh 
    state: directory
    owner: lvi
    group: lvi  
    mode: "u=rw,g=rw,o=r"

- name: Create .ssh/ directory in cso home directory  
  file: 
    path: /home/cso/.ssh 
    state: directory 
    owner: cso
    group: cso
    mode: "u=rw,g=rw,o=r"


- name: Loading lvi public key in /home/lvi/.ssh 
  copy: 
    src: /etc/ansible/roles/postinstall/files/lvi_rsa.pub
    dest: /home/lvi/.ssh/lvi_rsa.pub
    owner: lvi
    group: lvi
    mode: "u=rw,g=r,o=r"

- name: Adding the lvi public key to authorized_keys files.
    authorized_key: 
      user=charlie 
      key="{{ lookup('file', '/home/charlie/.ssh/id_rsa.pub') }}"




#- name: Adding the lvi public key to authorized_keys files.  
#  copy: 
#    src: /etc/ansible/roles/postinstall/files/lvi_rsa.pub
#    dest: /home/lvi/.ssh/authorized_keys
#    owner: lvi
#    group: lvi
#    mode: "u=rw,g=r,o=r"

- name: Loading cso public key in /home/cso/.ssh  
  copy: 
    src: /etc/ansible/roles/postinstall/files/cso_rsa.pub
    dest: /home/cso/.ssh/cso_rsa.pub
    owner: cso
    group: cso
    mode: "u=rw,g=r,o=r"

#- name: Adding the cso public key to authorized_keys files.  
#  copy: 
#    src: /etc/ansible/roles/postinstall/files/cso_rsa.pub
#    dest: /home/cso/.ssh/authorized_keys
#    owner: cso
#    group: cso
#    mode: "u=rw,g=r,o=r"

- name: Install fail2ban.
  apt: 
    pkg: fail2ban 
    state: present

- name: Deploy fail2ban config - ssh and ssh-ddos only. 
  template: 
    src: jail.local.j2 
    dest: /etc/fail2ban/jail.local
  notify: restart_fail2ban
