---

#Commandline : 
#ansible-playbook /etc/ansible/roles/timezone/setup.yml

- name: 'Yet another Ansible playbook to change the timezone'
  hosts: 
  become: true
  become_user: root
  become_method: sudo
  roles:
    - timezone