---

#Commandline : azerty123 will be the initial password 
#ansible-playbook -e “password=azerty123” /etc/ansible/roles/postinstall/setup.yml

- name: 'Postinstall routines on Ubuntu 14.04'
  hosts: newservers
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - postinstall