---
## Prerequisites docker-engine 
- name: Install APT over https.
  apt: 
    name: apt-transport-https
    state: present

- name: Install APT over https suite.
  apt: 
    name: ca-certificates
    state: present

- name: Install apparmor.
  apt: 
    name: apparmor
    state: present

##The Docker module in Ansible requires docker-py to interact with docker

- name: Install dependencies
  apt: 
    name: "{{ item }}" 
    update_cache: yes
  with_items: 
      - python-dev
      - python-setuptools

- name: Install pip
  easy_install: 
    name: pip 

- name: Install docker-py
  pip: 
    name: docker-py 
    state: present
    version: 1.1.0 

## Install docker-engine 
- name: Docker | Install ppa key
  apt_key: 
    id: 2C52609D 
    url: http://p80.pool.sks-keyservers.net/pks/lookup?op=get&search=0x58118E89F3A912897C070ADBF76221572C52609D 
    state: present

- name: Docker | Install ppa
  apt_repository: 
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' 
    state: present

- name: Refresh apt cache
  apt: 
    update_cache: yes

- name: Docker Engine | Install package
  apt: 
    name: docker-engine 
    state: present

## Check service
- name: Docker | Check service daemon
  service: 
    name: docker 
    state: started