#!/bin/sh
echo -e '

              _
 ___  ___ __ _| | _____      ____ _ _   _
/ __|/ __/ _` | |/ _ \ \ /\ / / _` | | | |
\__ \ (_| (_| | |  __/\ V  V / (_| | |_| |
|___/\___\__,_|_|\___| \_/\_/ \__,_|\__, |
                                    |___/
---------------------------------------------------------------------------------------------------------------------------

Welcome @ cloud.minsys.io :-)
visit : www.minsys.io | ask any Q : support@minsys.io

---------------------------------------------------------------------------------------------------------------------------

                    *****                                                       ,((((              
                    *****                                                       ,((((              
 ***** ****  ****   *****  ***** ***,     *****   ****   ****   *****           ,((((    *(((((    
 *****************  *****  ***********  *********  ****  **** *********         ,((((   (((((((((  
 *****  ****  ****  *****  ***** .**** *****  **** ****  ***  ****   ***        ,((((  ((((  ((((/ 
 *****  ****  ****  *****  ***** .****  *****       *** ****  ******            ,((((  ((((  ((((( 
 *****  ****  ****  *****  ***** .****   ******,    *******.    ******          ,((((  ((((  ((((( 
 *****  ****  ****  *****  ***** .****     .*****    ******       *****,        ,((((  ((((  ((((( 
 *****  ****  ****  *****  ***** .****   **  *****   ******    **   ****        ,((((  ((((  ((((( 
 *****  ****  ****  *****  ***** .****  *********    .****    **********  ,,,,  ,((((  ((((((((((  
 *****  ****  ****  *****  ***** .****    ******     .****      ******    ,,,,  ,((((    ((((((/   
                                                   ******                                          
                                                   ****  

--------------------------WARNING--------WARNING--------WARNING-------WARNING--------WARNING-------------------------------

This is a private computer system which is restricted to authorized individuals.

We reserve the right to view, monitor and record activity on the system without notice or permission.
Any information obtained by monitoring, reviewing or recording is subject to review by law enforcement
organizations in connection with the investigation or prosecution of possible criminal activity on the system.

If you are not an authorized user of this system or do not consent to continued monitoring, exit the system at this time.

Enjoy,
The minsys.io team !

---------------------------------------------------------------------------------------------------------------------------
'