---
#ansible-playbook /etc/ansible/roles/setup_postinstall-scw.yaml

- name: 'Postinstall Routine for Scaleway hosts'
  hosts: scw_newinstances
  vars_prompt:
  - name: "prompted_fqdn"
    prompt: "Please enter the fqdn of this new host - hostname.env.scw.cloud.minsys.io. env:lab,int,uat,prd."
    private: no 
  roles:
    - dist_update_upgrade-scw
    - timezone-scw
    - etc_hosts-scw
    - addgroups_initial-scw
    - adduser_lvi-scw
    - adduser_cso-scw
    - ssh_config-scw
    - fail2ban-scw
    - motd-scw
    - add_pkgs-scw
  post_tasks:
    - name:  Restart rsyslog to sync with newly intalled timezone 
      service: name=rsyslog state=restarted
