- name: Adding the root public key to authorized_keys files.
  become: true
  become_user: root
  become_method: sudo
  authorized_key: 
    user: root
    key: "{{ lookup('file', '/root/.ssh/ovh-root_rsa.pub') }}"
